My_Movie_Db_Website/config/urls.py
from django.contrib import admin
from django.urls import path, include
import core.urls ,user.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core'))
  

]

My_Movie_Db_Website/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieList.as_view(), name = 'MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name = 'MovieDetail'),
]

My_Movie_Db_Website/user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_view

app_name = 'user'

urlpatterns = [
    path('register', views.RegisterView.as_view(),
    name='register'),

    path('login', auth_view.LoginView.as_view(), name='login'),

    path('logout', auth_view.LogoutView.as_view(), name='logout')

]

My_Movie_Db_Website/core/models.py
from django.db import models
from django.conf import settings
from django import forms

# Create your models here.
class MovieManager(models.Manager):

    def all_with_related_person(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')

        return qs
        
class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance Suggested'),
        (RATED_R, 'R - Restricted'),
    ) 

    title = models.CharField(max_length=200)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices = RATINGS,
        default = NOT_RATED
    )

    runtime = models.PositiveIntegerField()
    website = models.URLField(
        blank = True
    )

    director = models.ForeignKey(
        to = 'Person',
        on_delete = models.SET_NULL,
        related_name = 'directed',
        null=True,
        blank = True
    )

    writers = models.ManyToManyField(
        to = 'Person',
        related_name = 'writing_credits',
        blank = True
    )

    actors = models.ManyToManyField(
        to = 'Person',
        through = 'Roles',
        related_name='acting_credits',
        blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{}({})'.format(self.title, self.year)

class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed', 'writing', 'role_set__movies')

class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)

    born = models.DateField()
    died = models.DateField(null = True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(self.last_name, self.first_name,
            self.born, self.died)

        return '{}, {} ({})'.format(self.last_name, self.first_name, self.born)

class Roles(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete = models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie', 'person', 'name') 
    
class VoteManager(models.Model):
    def get_vote_or_unsaved_blank(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie = movie, user = user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "👍",),
        (DOWN, "👎",),
    )

    value = models.SmallIntegerField(
        choices = VALUE_CHOICES,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete= models.CASCADE
    )

    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
    )

    voted_on = models.DateTimeField(
        auto_now=True
    )

    objects = VoteManager()
    
    class Meta:
        unique_together = ('user','movie')

My_Movie_Db_Website/user/models.py
from django.db import models

# Create your models here.

My_Movie_Db_Website/core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from core.models import Vote, Movie

class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget = forms.HiddenInput,
        queryset = get_user_model().objects.all(),
        disabled =True
    )

    movie = forms.ModelChoiceField(
        widget = forms.HiddenInput,
        queryset = Movie.objects.all(),
        disabled = True
    )
    fields = ('value', 'user', 'movie')

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie')
            

My_Movie_Db_Website/core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from core.models import Movie, Person
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import CreateView
from core.forms import VoteForm
# Create your views here.

class MovieList(ListView):
    model = Movie
    paginate_by = 10

class MovieDetail(DetailView):
    queryset = (
        Movie.objects.all_with_related_person()
    )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs) 
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie = self.object,
                user = self.request.user
            )
        
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs = {
                        'movie_id' : vote.movie.id,
                        'pk': vote.id
                    }
                )
            else:
                vote_form_url = reverse(
                    'core:CreateVote',
                    kwargs = {
                        'movie_id':self.object.id
                    }
                )

            vote_form = VoteForm(instance=Vote)
            ctx['vote_form']=vote_form
            ctx['vote_form_url'] = vote_form_url
        
        return ctx

class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super.get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial()
    
    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs ={
                'pk':movie_id
            }
        )
    
    def render_to_response(self, context, **response_kwargs):
        movie_id  = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs = {'pk': movie_id}
        )
        return redirect(
            to=movie_detail_url
        )

My_Movie_Db_Website/user/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
# Create your views here.

class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('core:MovieList')

My_Movie_Db_Website/core/templates/core/MovieList.html
{% extends 'base.html' %}

{% block title %}
    All the movies
{% endblock %}

{% block main %}
<ul>
    {% for movie in object_list %}
        <li>
            <a href = "{% url 'core:MovieDetail' pk=movie.id %}">
                {{ movie }}
            </a>
        </li>
    {% endfor%}
</ul>

{% if is_paginated %}
    <nav>
        <ul class="pagination">
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page=1" class="page-link">First</a>
            </li>
            {% if page_obj.has_previous %}
                <li class = "page-item">
                    <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number}}"
                    class="page-link">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item active">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
                class="page-link">
                    {{ page_obj.number }}    
                </a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
                        {{ page_obj.next_page_number}}
                    </a>
                </li>
            {% endif %}
            <li class="page-item">
                <a href = "{% url 'core:MovieList' %}?page=last" class="page-link">
                    Last
                </a>
            </li>
        </ul>
    </nav>
    {% endif %}
{% endblock %}

My_Movie_Db_Website/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
    <h1>{{ object }}</h1>
    <p class= "lead">
        {{ object.plot }}
    </p>
{% endblock %}

{% block sidebar %}
    <div>
        This movie is rated:
        <span class="badge badge-primary">
            {{ object.get_rating_display }}
        </span>
    </div>

    <div>
        {% if vote_form %}
            <form method="POST" action="{{ vote_form_url }}">
                {% csrf_token %}
                {{ vote_form.as_p }}
                <button class="btn btn-primary">Vote</button>
            </form>
        {% else %}
         <p>LogIn to vote fot this Movie</p>
        {% endif %}
    </div>
{% endblock %}

My_Movie_Db_Website/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
  All The Movies
{% endblock %}

{% block main %}
  <ul >
    {% for movie in object_list %}
      <li >
        <a href="{% url 'core:MovieDetail' pk=movie.id %}" >
          {{ movie }}
        </a >
      </li >
    {% endfor %}
  </ul >
  {% if is_paginated %}
    <nav >
      <ul class="pagination" >
        <li class="page-item" >
          <a
            href="{% url 'core:MovieList' %}?page=1"
            class="page-link"
          >
            First
          </a >
        </li >
        {% if page_obj.has_previous %}
          <li class="page-item" >
            <a
              href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
              class="page-link"
            >
              {{ page_obj.previous_page_number }}
            </a >
          </li >
        {% endif %}
        <li class="page-item active" >
          <a
            href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
            class="page-link"
          >
            {{ page_obj.number }}
          </a >
        </li >
        {% if page_obj.has_next %}
          <li class="page-item" >
            <a
              href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
              class="page-link"
            >
              {{ page_obj.next_page_number }}
            </a >
          </li >
        {% endif %}
        <li class="page-item" >
          <a
            href="{% url 'core:MovieList' %}?page=last"
            class="page-link"
          >
            Last
          </a >
        </li >
      </ul >
    </nav >
  {% endif %}
{% endblock %}

My_Movie_Db_Website/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
<h1> {{ object }}</h1>
<h2> Actor </h2>
<ul>
    {% for role in object.role_set.all %}
        <li>
            <a href= "{% url core:MovieDetail role.movie.id %}">
                {{ role.movie }}
            </a>:
            {{ role.name }}
        </li>
        {% endfor %}
</ul>

<h2>Writer</h2>
<ul>
    {% for movie in object.writing_credits.all %}
        <li>
            <a href="{% url 'core:MovieDetail' movie.id %}"> {{ movie }}</a>
        </li>
    {% endfor %}
</ul>
<h2>Directors</h2>
<ul>
    {% for movies in object.directed.all %}
        <li>
            <a href="{% url 'core:MovieDetail' movie.id %}">{{ movie }}</a>
        </li>
    {% endfor %}
</ul>

My_Movie_Db_Website/templates/base.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="UTF-8">
        <meta 
            name= "viewport"
            content = "width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
            rel="stylesheet">
        
            <title>
                {% block title %} MyMDB {% endblock %}
            </title>
            <style>
                .mymdb-masthead{
                    background-color: #eeeeee;
                    margin-bottom: 1em;
                }
            </style>
    </head>
    <body>
        <div class="mymdb-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar -brand">MyMDB</div>
                    <a
                        class="nav-link"
                        href="{% url 'core:MovieList' %}"
                    >
                    Movies
                    </a>
                </nav>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-8 mymdb-main">
                    {% block main %}{% endblock %}
                </div>
                <div class="col-sm-3 offset-sm-1 mymdb-sitebar">
                    {% block sidebar %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

My_Movie_Db_Website/user/templates/user/register.html
{% extends "base.html" %}
{% block main %}
    <h1>Register for MyMDB</h1>
    
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"> Register </button>
    </form>
{% endblock %}